version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: .
    ports:
      - "7777:7777"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
